---

icinga2_mode: satellite

icinga2_masters:
  instance:

# icinga2_satellites: satellite
# icinga2_satellites:
#   satellite:
#     satellite:
#       ip: 10.15.0.30

icinga2_host_object:
  localhost:
    import: generic-host
    address: '{{ ansible_default_ipv4.address }}'
    display_name: "{{ ansible_fqdn }}"
    vars: |
      os = "Linux"
      dist = "{{ ansible_distribution }}"
      dist_ver = "{{ ansible_distribution_version }}"
      satellite = true
      disks = {
        "disk /" = {
          disk_partitions = "/"
        }
      }

...
