---

- name: merge icinga2_apply_service configuration between defaults and custom
  set_fact:
    icinga2_apply_service: "{{ icinga2_defaults_apply_service |
      combine( icinga2_apply_service, recursive=True ) }}"

- name: merge icinga2_defaults_checkcommands configuration between defaults and custom
  set_fact:
    icinga2_checkcommands: "{{ icinga2_defaults_checkcommands |
      combine( icinga2_checkcommands, recursive=True ) }}"

- name: global templates on primary master
  block:
    - name: create global-templates file for service definitions
      template:
        src: etc/icinga2/zones.d/global-templates/services.conf.j2
        dest: /etc/icinga2/zones.d/global-templates/services.conf
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_group }}"
        mode: 0660
      notify:
        - check configuration
        - restart icinga2

    - name: create global-templates file for commands definitions
      template:
        src: etc/icinga2/zones.d/global-templates/commands.conf.j2
        dest: /etc/icinga2/zones.d/global-templates/commands.conf
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_group }}"
        mode: 0660
      notify:
        - check configuration
        - restart icinga2

    - name: create global-templates file for functions definitions
      template:
        src: etc/icinga2/zones.d/global-templates/functions.conf.j2
        dest: /etc/icinga2/zones.d/global-templates/functions.conf
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_group }}"
        mode: 0660
      notify:
        - check configuration
        - restart icinga2

    - name: create global-templates file for event commands
      template:
        src: etc/icinga2/zones.d/global-templates/eventcommands.conf.j2
        dest: /etc/icinga2/zones.d/global-templates/eventcommands.conf
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_group }}"
        mode: 0660
      notify:
        - check configuration
        - restart icinga2

  when:
    - icinga2_primary_master is defined
    - icinga2_primary_master == ansible_fqdn

...
