---

- name: check installed
  include_tasks: check_installed.yml

- name: detect icinga2_user
  icinga2_prepared_vars:
    variable: ICINGA2_USER
  register: _icinga2_user

- name: detect icinga2_group
  icinga2_prepared_vars:
    variable: ICINGA2_GROUP
  register: _icinga2_group

- name: define icinga2_user to '{{ _icinga2_user.value }}'
  set_fact:
    icinga2_user: "{{ _icinga2_user.value }}"
  when:
    - _icinga2_user.value is defined

- name: define icinga2_group to '{{ _icinga2_group.value }}'
  set_fact:
    icinga2_group: "{{ _icinga2_group.value }}"
  when:
    - _icinga2_group.value is defined

- name: create custom fact file
  template:
    src: facts.d/icinga2.fact.j2
    dest: /etc/ansible/facts.d/icinga2.fact
    owner: root
    group: root
    mode: 0755

- name: create sudo rules for icinga
  template:
    src: etc/sudo.j2
    dest: /etc/sudoers.d/icinga
    mode: 0440
    validate: 'visudo -cf %s'

- name: do facts module to get latest information
  setup:

...
