---

- name: define primary icinga2 master
  set_fact:
    icinga2_primary_master: "{{ icinga2_masters | reorder_master }}"

- include: preparations.yml
  become: true
  tags:
    - icinga2

# - name: "create a ticket from icinga2 master for the secondary master '{{ ansible_fqdn }}'"
#   icinga2_ticket:
#     common_name: "{{ icinga2_certificate_cn }}"
#     salt: "{{ icinga2_salt }}"
#   #shell: |
#   #  icinga2 pki ticket --cn {{ icinga2_certificate_cn }}
#   register: ticket
#   delegate_to: "{{ icinga2_primary_master }}"
#   #when: icinga2_salt is defined
#   when: icinga2_primary_master is defined and icinga2_primary_master != ansible_fqdn
#
# - debug:
#     msg:
#       - "ticket        : {{ ticket }}"

- include: install.yml
  become: true
  tags:
    - icinga2

- include_tasks: master.yml
  when: icinga2_mode == 'master'
  tags:
    - icinga2

- include_tasks: satellite.yml
  when: icinga2_mode == 'satellite'
  tags:
    - icinga2

- include_tasks: service.yml
  tags:
    - icinga2

# ---------------------------------------------------------------------------------------

- include_tasks: master/backup.yml
  when:
    - icinga2_mode == 'master'
  tags:
    - icinga2
    - backup

- include_tasks: master/restore.yml
  when:
    - icinga2_mode == 'master'
  tags:
    - icinga2
    - restore

- include_tasks: downtime.yml
  when:
    - icinga2_mode == 'master'
    - icinga2_downtime_comment is defined and icinga2_downtime_comment | length != 0
    - icinga2_downtime_duration is defined and icinga2_downtime_duration | int != 0
    - icinga2_api.user is defined
    - icinga2_api.password is defined
    - icinga2_downtime_system_name is defined
  tags:
    - icinga2
    - downtime_schedule
    - downtime_remove
