---

- name: prepare
  include_tasks: prepare.yml
  tags:
    - icinga2-install

- name: install
  include_tasks: install.yml
  tags:
    - icinga2-configure
    - icinga2-install

- name: facts
  include_tasks: facts.yml
  tags:
    - icinga2-configure
    -
- name: master
  include_tasks: master.yml
  when:
    - icinga2_mode == 'master'
  tags:
    - icinga2-configure
    - icinga2-master

- name: satellite
  include_tasks: satellite.yml
  when:
    - icinga2_mode == 'satellite'
  tags:
    - icinga2-configure
    - icinga2-satellite

- name: service
  include_tasks: service.yml
  tags:
    - icinga2-service

# ---------------------------------------------------------------------------------------

- include_tasks: master/backup.yml
  when:
    - icinga2_mode == 'master'
  tags:
    - icinga2
    - backup

- include_tasks: master/restore.yml
  when:
    - icinga2_mode == 'master'
  tags:
    - icinga2
    - restore

- include_tasks: downtime.yml
  when:
    - icinga2_mode == 'master'
    - icinga2_downtime_comment is defined
    - icinga2_downtime_comment | length != 0
    - icinga2_downtime_duration is defined
    - icinga2_downtime_duration | int != 0
    - icinga2_api.user is defined
    - icinga2_api.password is defined
    - icinga2_downtime_system_name is defined
  tags:
    - icinga2
    - downtime_schedule
    - downtime_remove

...
