---

- name: re-read ansible facts
  setup:

- name: include OS specific configuration
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yml"
        - default.yml
      skip: true

- name: define primary icinga2 master
  set_fact:
    icinga2_primary_master: "{{ icinga2_masters | primary_master }}"

- name: define satellite zone
  block:

    - name: define satellite zone, when icinga2_satellites are configured
      set_fact:
        icinga2_satellite_zone: "{{ icinga2_satellites | satellite_zone(ansible_fqdn) }}"
      when:
        - icinga2_satellites is defined
        - icinga2_satellites | count > 0

    - name: define satellite zone, when icinga2_satellites are empty
      set_fact:
        icinga2_satellite_zone: "{{ ansible_fqdn }}"
      when:
        - icinga2_satellites is defined
        - icinga2_satellites | count == 0
  when:
    - icinga2_mode == 'satellite'

- name: assert missing primary master
  assert:
    that:
      - icinga2_primary_master | length != 0
    msg: primary icinga2 master is missing
    quiet: true

- name: assert wrong primary master
  assert:
    that: ansible_fqdn in (icinga2_masters | list) or
       icinga2_mode == 'master' and
       icinga2_primary_master == ansible_fqdn
    msg: primary icinga2 master is not identical with ansible_fqdn ('{{ icinga2_primary_master }}' vs. '{{ ansible_fqdn }}')
    quiet: true
  when:
    - icinga2_validate_primary_master
    - icinga2_mode == 'master'

- name: information
  debug:
    msg:
      - "fqdn           : {{ ansible_fqdn }}"
      - "mode           : {{ icinga2_mode }}"
      - "primary_master : {{ icinga2_primary_master }}"
      - "satellite_zone : {{ icinga2_satellite_zone | default({}) }}"
      - "certificate_cn : {{ icinga2_certificate_cn }}"
      - "masters        : {{ icinga2_masters | list }}"

# ----------------------------------------------------------------------------------

# read a present salt from ansible facts
#
- name: define icinga2_salt from local fact
  set_fact:
    icinga2_salt: "{{ ansible_local.icinga2.salt }}"
  when:
    - ansible_local.icinga2 is defined
    - ansible_local.icinga2.salt is defined
    - ansible_local.icinga2.salt | length != 0
    - icinga2_salt != ansible_local.icinga2.salt

- name: assert missing salt
  assert:
    that:
      - icinga2_salt | length != 0
    msg: icinga2 salt is missing
    quiet: true

- name: merge icinga2 filelogger configuration between defaults and custom
  set_fact:
    icinga2_filelogger: "{{ icinga2_filelogger_default |
      combine( icinga2_filelogger, recursive=True ) }}"

- name: merge icinga2 api configuration between defaults and custom
  set_fact:
    icinga2_api: "{{ icinga2_api_default |
      combine( icinga2_api, recursive=True ) }}"

- name: merge icinga2 timeperiod configuration between defaults and custom
  set_fact:
    icinga2_timeperiod: "{{ icinga2_timeperiod_default |
      combine( icinga2_timeperiod, recursive=True ) }}"

- block:
    - name: find OS specific plugins directory
      find:
        paths: "/usr/lib/monitoring-plugins,/usr/lib/nagios,/usr/lib64/nagios"
        file_type: directory
        patterns:
          - "plugins"
        recurse: true
      register: found_directory

    - name: define monitoring_plugins_directory
      set_fact:
        monitoring_plugins_directory: "{{ found_directory.files | sort(attribute='path', reverse=True) | map(attribute='path') | list | first }}"
      when:
        - found_directory.files is defined
        - found_directory.files | count > 0
  when:
    - ansible_os_family | lower != 'archlinux'

# ----------------------------------------------------------------------------------

# debian based
#
- block:
    - name: add icinga2 GPG key
      apt_key:
        id: F51A91A5EE001AA5D77D53C4C6E319C334410682
        url: https://packages.icinga.com/icinga.key

    - name: add icinga2 repo sources
      template:
        src: etc/apt/icinga2.list.j2
        dest: /etc/apt/sources.list.d/icinga2.list
        mode: 0644
  when:
    - ansible_os_family | lower == 'debian'
    - icinga2_use_external_repo | bool

# redhat based
#
- block:
    - name: import EPEL GPG key
      rpm_key:
        key: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present

    - name: install EPEL repository
      yum_repository:
        name: epel
        state: present
        description: Extra Packages for Enterprise Linux {{ ansible_distribution_major_version }} - $basearch
        baseurl: http://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/$basearch
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch&infra=$infra&content=$contentdir
        failovermethod: priority
        gpgcheck: 1
        enabled: 1

    - name: import icinga2 GPG key
      rpm_key:
        key: https://packages.icinga.com/icinga.key
        state: present

    - name: install icinga2 repository
      yum_repository:
        name: icinga-stable-release
        state: present
        description: ICINGA (stable release for epel)
        baseurl: https://packages.icinga.com/epel/$releasever/release/
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ICINGA
        gpgcheck: 1
        enabled: 1
  when:
    - ansible_os_family | lower == 'redhat'
    - icinga2_use_external_repo | bool

# arch-linux based
#
- block:
    - name: install build tools
      package:
        name: "{{ item }}"
        state: present
      loop:
        - base-devel
        - cmake

    - name: create sudo rules for aur_builder
      copy:
        content: '%aur_builder ALL=(ALL) NOPASSWD: ALL'
        dest: /etc/sudoers.d/aur
        mode: 0640
        validate: visudo -cf %s

    - name: create build group
      group:
        name: aur_builder

    - name: create build user
      user:
        name: aur_builder
        group: aur_builder
  when:
    - ansible_os_family | lower == 'archlinux'
    - icinga2_use_external_repo | bool

- name: update package cache
  package:
    update_cache: true

- name: install requirements
  package:
    name: "{{ icinga2_requirements | union(icinga2_os_requirements) }}"
    state: present

# see https://stackoverflow.com/questions/67273590/pip-21-1-cant-import-invalidschemecombination
- name: fix broken pip package
  block:
    #
    - name: remove python-pip package
      package:
        name: python-pip
        state: absent
    - name: use python module ensurepip
      command: |
        python -m ensurepip

    - name: update pip3 to latest
      pip:
        name: pip
        state: latest
        executable: pip3
        umask: "0022"
  when:
    - ansible_os_family | lower == 'archlinux'

- name: get latest system information
  setup:

- name: create sudo rules for icinga
  template:
    src: etc/sudo.j2
    dest: /etc/sudoers.d/icinga
    mode: 0440
    validate: 'visudo -cf %s'

- name: make sure ansible local facts directory exists
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755

...
