---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: database
    image: "diodonfrost/ansible-${DISTRIBUTION:-debian:10}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    docker_networks:
      - name: icinga2
        ipam_config:
          - subnet: "10.15.0.0/16"
            gateway: "10.15.0.254"
    networks:
      - name: icinga2
        ipv4_address: "10.15.0.10"

  - name: instance
    image: "diodonfrost/ansible-${DISTRIBUTION:-debian:10}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - icinga
    networks:
      - name: icinga2
        ipv4_address: "10.15.0.20"

  - name: satellite
    image: "diodonfrost/ansible-${DISTRIBUTION:-debian:10}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - icinga
    networks:
      - name: icinga2
        ipv4_address: "10.15.0.30"

provisioner:
  name: ansible
  config_options:
    defaults:
      deprecation_warnings: True
      stdout_callback: yaml

scenario:
  test_sequence:
    # - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
