---

- name: information
  hosts: all
  gather_facts: true

  pre_tasks:
    - debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"
          - "ansible tasks        : {{ ansible_run_tags }}"
      tags:
        - always

- name: install icinga2
  hosts: icinga
  any_errors_fatal: true

  roles:
    - role: ansible-icinga2
      when:
        - ansible_run_tags | intersect(["all","icinga2_install"]) | count > 0
      tags:
        - icinga2_install

- name: configure icinga2 primary
  hosts: icinga_primary
  any_errors_fatal: true

  roles:
    - role: ansible-icinga2
      when:
        - ansible_run_tags | intersect(["all","icinga2_configure","icinga2_master"]) | count > 0
      tags:
        - icinga2_configure

- name: configure icinga2 satellite
  hosts: icinga_satellite
  any_errors_fatal: true

  roles:
    - role: ansible-icinga2
      when:
        - ansible_run_tags | intersect(["all","icinga2_configure","icinga2_satellite"]) | count > 0
      tags:
        - icinga2_configure

...
