---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 .

platforms:
  - name: database
    image: "bodsch/ansible-debian:11"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    docker_networks:
      - name: icinga2
        ipam_config:
          - subnet: "10.15.0.0/24"
            gateway: "10.15.0.254"
    networks:
      - name: icinga2
        ipv4_address: "10.15.0.10"

  - name: instance
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - icinga
      - icinga_primary
    networks:
      - name: icinga2
        ipv4_address: "10.15.0.20"

  - name: satellite
    image: "bodsch/ansible-${DISTRIBUTION:-debian:11}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - icinga
      - icinga_satellite
    networks:
      - name: icinga2
        ipv4_address: "10.15.0.30"

provisioner:
  name: ansible
  #env:
  #  ANSIBLE_LOCAL_TEMP: "${WORKSPACE:-$HOME}/.ansible/tmp"
  #  ANSIBLE_REMOTE_TMP: /tmp
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: true
      stdout_callback: yaml
      callbacks_enabled: profile_tasks
      gathering: smart
      fact_caching: jsonfile
      fact_caching_timeout: 8640
      fact_caching_connection: "${MOLECULE_EPHEMERAL_DIRECTORY}/ansible_facts"

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    # - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
