---

- block:
    - name: enable api feature
      icinga2_feature:
        name: api
        state: present
      notify:
        - check configuration
        - restart icinga2
      tags:
        - icinga2
        - features

    - name: configure api feature
      template:
        src: etc/icinga2/features/api.conf.j2
        dest: /etc/icinga2/features-available/api.conf
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_group }}"
        mode: 0660
  when: icinga2_master_features_enabled | join('|') | regex_search('api')
