---

- block:
    - name: enable icingadb feature
      icinga2_feature:
        name: icingadb
        state: present
      notify:
        - check configuration
        - restart icinga2
      tags:
        - icinga2
        - features

    - name: configure icingadb feature
      template:
        src: etc/icinga2/features/icingadb.conf.j2
        dest: /etc/icinga2/features-available/icingadb.conf
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_group }}"
        mode: 0660
      notify:
        - check configuration
        - restart icinga2
  when:
    - icinga2_master_features_enabled | join('|') | regex_search('icingadb')

...
