---

- name: install packages for support databases
  package:
    name: "{{ icinga2_mariadb_packages }}"
    state: present

- name: python support
  block:
    - name: create requirements.txt
      template:
        src: requirements.txt.j2
        dest: /tmp/icinga2-requirements.txt
        mode: 0660

    - name: do facts module to get latest information
      setup:

    - debug:
        msg:
          - "{{ ansible_python }}"
          - "{{ ansible_python_interpreter | default('') }}"

    - name: ensure python bindings for mariadb packages 1st
      pip:
        # executable: pip3
        requirements: /tmp/icinga2-requirements.txt
        state: present
      register: pip_install
      ignore_errors: true
      # no_log: true

    # missing 'libmariadbclient-dev'?

    - block:
        - name: install build essentials
          package:
            name: "{{ icinga2_mariadb_build_packages }}"
            state: present

        - name: ensure python bindings for mariadb packages 2nd
          pip:
            requirements: /tmp/icinga2-requirements.txt
            state: present

        - name: uninstall build essentials
          package:
            name: "{{ icinga2_mariadb_build_packages }}"
            state: absent
      when:
        - pip_install.failed
        - icinga2_mariadb_build_packages is defined
        - icinga2_mariadb_build_packages | length > 0

    # - name: remove requirements.txt
    #   file:
    #     path: /tmp/icinga2-requirements.txt
    #     state: absent
  when:
    - icinga2_mariadb_python_packages is defined
    - icinga2_mariadb_python_packages | length > 0

# - name: install python packages for support databases
#   pip:
#     executable: pip3
#     name: "{{ item }}"
#     # executable: "{{ 'pip3' if ansible_python.version.major > 2 else 'pip2' }}"
#     state: present
#   loop:
#     - "{{ icinga2_mariadb_python_packages }}"

- name: install icinga2-ido package
  package:
    name: icinga2-ido-mysql
    state: present
  when:
    - ansible_os_family | lower != 'archlinux'

- block:
    - name: create database upgrade script
      template:
        src: database-upgrade.sh.j2
        dest: /usr/local/bin/database-upgrade.sh
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_group }}"
        mode: 0750

    - name: check if configured database are available
      wait_for:
        host: "{{ icinga2_ido.host }}"
        port: "{{ icinga2_ido.port }}"
        delay: 1              # No wait before first check (sec)
        timeout: 5            # Stop checking after timeout (sec)
      ignore_errors: false
      retries: 10
      delay: 10

    - name: get mysql ido version
      icinga2_ido_version:
        dba_host: "{{ icinga2_ido.host }}"
        dba_user: "{{ icinga2_ido.user }}"
        dba_password: "{{ icinga2_ido.password }}"
        dba_database: "{{ icinga2_ido.database }}"
      register: _mysql_ido_version

    - name: create the mysql ido schema
      mysql_db:
        name: "{{ icinga2_ido.database }}"
        login_host: "{{ icinga2_ido.host }}"
        login_user: "{{ icinga2_ido.user }}"
        login_password: "{{ icinga2_ido.password }}"
        state: import
        target: "{{ icinga2_ido.mysql.schema_file }}"
      register: mysql_create_ido_schema
      changed_when: false
      check_mode: false
      when:
        - not _mysql_ido_version.exists

    - name: update database schema  # noqa 'command-instead-of-shell'
      command:
        cmd: /usr/local/bin/database-upgrade.sh
      changed_when: false
      # no_log: false
  when:
    - icinga2_primary_master is defined
    - icinga2_primary_master == ansible_fqdn

- name: configure ido-mysql feature
  template:
    src: etc/icinga2/features/ido-mysql.conf.j2
    dest: /etc/icinga2/features-available/ido-mysql.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0660

- name: enable ido-mysql feature
  icinga2_feature:
    name: ido-mysql
    state: present
  notify:
    - restart icinga2
  tags:
    - icinga2
    - features

...
