---

- name: install packages for support databases
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ icinga2_mariadb_packages }}"

- name: install python packages for support databases
  pip:
    executable: pip3
    name: "{{ item }}"
    # executable: "{{ 'pip3' if ansible_python.version.major > 2 else 'pip2' }}"
    state: present
  loop:
    - "{{ icinga2_mariadb_python_packages }}"

- name: install icinga2-ido package
  package:
    name: icinga2-ido-mysql
    state: present

- block:
    - name: create database upgrade script
      template:
        src: database-upgrade.sh.j2
        dest: /usr/local/bin/database-upgrade.sh
        owner: "{{ icinga2_user }}"
        group: "{{ icinga2_group }}"
        mode: 0750

    - name: check if configured database are available
      wait_for:
        host: "{{ icinga2_ido.host }}"
        port: "{{ icinga2_ido.port }}"
        delay: 1              # No wait before first check (sec)
        timeout: 5            # Stop checking after timeout (sec)
      ignore_errors: false
      retries: 10
      delay: 10

    - name: check mysql database version
      shell: >
        mysql \
          --host={{ icinga2_ido.host }} \
          --user={{ icinga2_ido.user }} \
          --password={{ icinga2_ido.password }} \
          --batch \
          --skip-column-names \
          --execute \
          "select version from {{ icinga2_ido.database }}.icinga_dbversion"
      register: _mysql_ido_version
      changed_when: false
      ignore_errors: true
      no_log: true

    - name: create the mysql ido schema
      mysql_db:
        name: "{{ icinga2_ido.database }}"
        login_host: "{{ icinga2_ido.host }}"
        login_user: "{{ icinga2_ido.user }}"
        login_password: "{{ icinga2_ido.password }}"
        state: import
        target: "{{ icinga2_ido.mysql.schema_file }}"
      register: mysql_create_ido_schema
      changed_when: false
      check_mode: false
      when: _mysql_ido_version.stdout | string | length == 0

    - name: update database schema  # noqa 305
      command:
        cmd: /usr/local/bin/database-upgrade.sh
      changed_when: false
      # no_log: false
  when: icinga2_primary_master is defined and icinga2_primary_master == ansible_fqdn

- name: configure ido-mysql feature
  template:
    src: etc/icinga2/features/ido-mysql.conf.j2
    dest: /etc/icinga2/features-available/ido-mysql.conf
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    mode: 0660

- name: enable ido-mysql feature
  icinga2_feature:
    name: ido-mysql
    state: present
  notify:
    - restart icinga2
  tags:
    - icinga2
    - features
