---
- name: converge
  hosts: instance
  any_errors_fatal: false

  environment:
    NETRC: ''
    http_proxy: "{{ lookup('env','HTTP_PROXY') }}"
    https_proxy: "{{ lookup('env','HTTPS_PROXY') }}"

  pre_tasks:
    - name: detect python3
      stat:
        path: /usr/bin/python3
      register: __stat_present_python3
      changed_when: not __stat_present_python3.stat.exists

    - name: set python3
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
      when:
        - ansible_python.version.major == 2
        - __stat_present_python3.stat.exists

    - name: Gathering Facts now
      setup:

  roles:
    - role: ansible-icinga2

  # tasks:
  #   # - include: ../../tasks/master/features.yml
  #   #   tags:
  #   #     - features
  #   - include: ../../tasks/downtime.yml
  #     vars:
  #       icinga2_master: '{{ ansible_default_ipv4.address }}'
  #       icinga2_api.user: root
  #       icinga2_api.password: foo
  #       icinga2_downtime_comment: Downtime for deployment
  #       icinga2_downtime_system_name: localhost
  #       icinga2_downtime_duration: 120
  #
  #     tags:
  #       - downtime_schedule
