---

- name: information
  hosts: all
  gather_facts: true

  pre_tasks:
    - debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"
          - "ansible tasks        : {{ ansible_run_tags }}"
      tags:
        - always

- name: install icinga2
  hosts: instance
  any_errors_fatal: true

  environment:
    NETRC: ''

  roles:
    - role: ansible-icinga2
      when:
        - ansible_run_tags | intersect(["all","icinga2_install"]) | count > 0
      tags:
        - icinga2_install

  # tasks:
  #   # - include: ../../tasks/master/features.yml
  #   #   tags:
  #   #     - features
  #   - include: ../../tasks/downtime.yml
  #     vars:
  #       icinga2_master: '{{ ansible_default_ipv4.address }}'
  #       icinga2_api.user: root
  #       icinga2_api.password: foo
  #       icinga2_downtime_comment: Downtime for deployment
  #       icinga2_downtime_system_name: localhost
  #       icinga2_downtime_duration: 120
  #
  #     tags:
  #       - downtime_schedule

- name: configure icinga2
  hosts: instance
  any_errors_fatal: true

  environment:
    NETRC: ''

  roles:
    - role: ansible-icinga2
      when:
        - ansible_run_tags | intersect(["all","icinga2_configure","icinga2_master"]) | count > 0
      tags:
        - icinga2_configure
