---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml

platforms:
#   - name: centos-7
#     image: paulfantom/centos-molecule:7
#     docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
#     privileged: true
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro
#
#   - name: centos-8
#     image: paulfantom/centos-molecule:8
#     docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
#     privileged: true
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro
#
#   - name: ubuntu-16
#     image: paulfantom/ubuntu-molecule:16.04
#     docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
#     privileged: true
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: ubuntu-18
    image: paulfantom/ubuntu-molecule:18.04
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

#   - name: debian-9
#     image: paulfantom/debian-molecule:9
#     docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
#     privileged: true
#     volumes:
#       - /sys/fs/cgroup:/sys/fs/cgroup:ro

  - name: debian-10
    image: paulfantom/debian-molecule:10
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro


provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    create: create.yml
    prepare: prepare.yml
    converge: playbook.yml
    destroy: destroy.yml

scenario:
  name: default
  test_sequence:
    # - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
