---
- name: prepare container
  hosts: all
  gather_facts: true

  pre_tasks:

    - name: update package cache
      apt:
        update_cache: true
      when:
        - ansible_os_family | lower == 'debian'

    - name: disable app armor
      shell: |
        sudo apt-get install apparmor-profiles
        sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
        sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      when:
        - ansible_os_family | lower == 'debian'

    - name: install netstat
      package:
        name: [ net-tools, iproute2 ]
        state: present
      when:
        - ansible_os_family | lower in [ 'archlinux', 'debian' ]

    - debug:
        msg:
          - "os family            : {{ ansible_os_family }}"
          - "distribution         : {{ ansible_distribution }}"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}"

  roles:
    - role: mariadb
    - role: monitoring-tools
