---
- name: prepare container
  hosts: all
  gather_facts: true

  pre_tasks:

    - block:
        - name: update package cache
          apt:
            update_cache: true

        - name: Install Backports repository on Debian Stretch
          apt_repository:
            repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
            state: present
            update_cache: true
          when:
            - ansible_distribution_release == 'stretch'

        - name: Install apt-transport-https on older Debian/Ubuntu versions
          apt:
            name:
              - apt-transport-https
          when:
            - ansible_distribution_release in ['jessie', 'stretch', 'xenial']
      when:
        - ansible_os_family | lower == 'debian'

    # # only for ubuntu .. with enabled apparmor, the mysql will not start!
    # #
    # - name: disable app armor
    #   block:
    #     - name: teardown apparmor
    #       shell:
    #         /etc/init.d/apparmor stop
    #         /etc/init.d/apparmor teardown
    #         update-rc.d apparmor remove
    #       when:
    #         - ansible_distribution_major_version | int == 18
    #
    #     - name: teardown apparmor
    #       shell: |
    #         /etc/init.d/apparmor stop
    #         update-rc.d apparmor remove
    #         systemctl stop snapd.apparmor
    #         systemctl disable snapd.apparmor
    #         systemctl mask snapd.apparmor
    #         systemctl stop snapd
    #         systemctl disable snapd
    #         systemctl mask snapd
    #         systemctl stop snapd.socket
    #         systemctl disable snapd.socket
    #         systemctl mask snapd.socket
    #         aa-teardown
    #         apt purge -y apparmor
    #         apt purge -y snapd
    #       when:
    #         - ansible_distribution_major_version | int == 20
    #
    #   when:
    #     - ansible_distribution | lower == 'ubuntu'

    - name: install netstat
      package:
        name: [ net-tools, iproute2 ]
        state: present
      when:
        - ansible_os_family | lower in [ 'archlinux', 'debian' ]

    - debug:
        msg:
          - "os family            : {{ ansible_os_family }}"
          - "distribution         : {{ ansible_distribution }}"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}"

  roles:
    - role: apparmor
    - role: snapd
    - role: monitoring-tools

- name: prepare container
  hosts: database
  gather_facts: true

  roles:
    - role: mariadb
