---
- name: prepare container
  hosts: all
  gather_facts: true

  vars:

    mysql_python_package_debian: "{{ 'python3-mysqldb' if ansible_python.version.major == 3 else 'python-mysqldb' }}"

    mysql_bind_address: 127.0.0.1
    mysql_max_connections: 20

    mysql_root_password_update: true

    mysql_databases:
      - name: icinga2_ido

    mysql_users:
      - name: icinga2_ido
        host: 127.0.0.1
        password: icinga2
        priv: "icinga2_ido.*:ALL"

  pre_tasks:

    - debug:
        msg:
          - "ansible_os_family                  : {{ ansible_os_family }}"
          - "ansible_distribution               : {{ ansible_distribution }}"
          - "ansible_distribution_major_version : {{ ansible_distribution_major_version }}"
          - "ansible_version                    : {{ ansible_version.full }}"
          - "ansible_python_version             : {{ ansible_python.version.major }}"

    - block:
        - name: Install required packages on Debian
          apt:
            # name:
            #   # required to add key to apt keyring
            #   - gnupg
            #   # required to verify icinga2 is running
            #   - procps
            update_cache: true

        - name: Install Backports repository on Debian Stretch
          apt_repository:
            repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
            state: present
            update_cache: true
          when:
            - ansible_distribution_release == 'stretch'

        - name: Install apt-transport-https on older Debian/Ubuntu versions
          apt:
            name:
              - apt-transport-https
          when:
            - ansible_distribution_release in ['jessie', 'stretch', 'xenial']

      when: ansible_os_family | lower == 'debian'

  roles:
    - role: mariadb
    - role: monitoring-tools
