---

- name: monitoring-tools
  src: https://github.com/bodsch/ansible-monitoring-plugins.git
  version: 1.0.0

- name: mariadb
  src: https://github.com/geerlingguy/ansible-role-mysql.git
  version: 3.3.0
