---

icinga2_salt: tmpams80tqx

icinga2_masters:
  instance:

icinga2_api:
  user:
    root:
      password: foo
      permissions: '*'

icinga2_ido:
  username: icinga2_ido
  password: icinga2
  host: database
  # socket: /var/lib/mysql/mysql.sock
  cleanup:
    acknowledgements_age: 24h
    hostchecks_age: 24h
    servicechecks_age: 24h

icinga2_master_features_enabled:
  - checker
  - api
  - ido-mysql
  - mainlog

icinga2_notification_apply_rules:
  #
  mail_host:
    # type: host
    # import: generic-host-notification
    users:
      - bodsch
    # user_groups: ""
    # interval: '2h'
    # extra_parameters: |
    #   vars.notification_logtosyslog = true
    # assign_where: "host.vars.notification.mail"

...
