---

- name: information
  hosts: all
  gather_facts: true

  pre_tasks:
    - name: update pacman system
      command: |
        pacman --refresh --sync --sysupgrade --noconfirm
      when:
        - ansible_distribution | lower == 'archlinux'

    - debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

- name: prepare container
  hosts: all
  gather_facts: true

  roles:
    - role: apparmor
    - role: snapd
    - role: monitoring-tools

- name: prepare container
  hosts: database
  gather_facts: true

  roles:
    - role: mariadb

- name: prepare influxdb
  hosts: influxdb
  gather_facts: true

  pre_tasks:
    - name: install pip
      package:
        name: python3-pip
        state: present

    # to fix https://github.com/mkayontour/ansible-influxdb/issues/9
    - name: add influxdata-archive_compat.key
      shell:
        cd /tmp/ ;
        curl https://repos.influxdata.com/influxdata-archive_compat.key > /tmp/influxdata-archive_compat.key &&
        echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c /tmp/influxdata-archive_compat.key' | sha256sum -c && cat /tmp/influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg
      when:
        - ansible_distribution | lower == 'debian'

  roles:
    - role: influxdb
