---

- name: snapd
  src: bodsch.snapd
  version: 1.1.2

- name: apparmor
  src: bodsch.apparmor
  version: 1.0.1

- name: monitoring-tools
  src: bodsch.monitoring_plugins
  version: 1.4.0

- name: mariadb
  src: bodsch.mariadb
  version: 2.2.13

- name: influxdb
  src: mkayontour.influxdb
  # src: https://github.com/mkayontour/ansible-influxdb.git
  # scm: git
  version: v1.0.0

...
