---
name: icinga2 primary with one satellite

on:
  schedule:
    - cron: "55 3 * * 0"
  workflow_dispatch:
  workflow_run:
    workflows:
      - "code linter"
    types:
      - completed

defaults:
  run:
    working-directory: 'ansible-icinga2'

jobs:
  deb:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}"
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:11
        ansible-version:
          - '6.1'

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-icinga2'

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      # See: https://github.com/geerlingguy/ansible-role-mysql/issues/422
      - name: Disable AppArmor
        run: |
            sudo apt-get install apparmor-profiles
            sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
            sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld

      - name: test with tox
        run: |
          tox -e ansible_$(printf "${{ matrix.ansible-version }}") \
            -- molecule test --scenario-name primary-with-satellite
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}
